"""
Drop-in replacement for the rendering half of summarize.py.
Keep everything above `def digest_to_text` unchanged — only these
two functions (plus the new `_tag_service` helper) are new.
"""
from __future__ import annotations

from datetime import date


# ---- service tagging -------------------------------------------------

_SERVICE_RULES = [
    ("APIM / AI Gateway", ("api management", "apim", "ai gateway", "mcp")),
    ("Logic Apps", ("logic app",)),
    ("Service Bus", ("service bus",)),
    ("Event Grid", ("event grid",)),
    ("Functions", ("azure function", "functions app", "durable function")),
    ("Integration Patterns", ("integration service environment", "ise ")),
    ("Industry AI", ("openai", "gpt-", "llm", "model", "anthropic", "claude", "gemini")),
]
_DEFAULT_SERVICE = "Other"

_SERVICE_COLORS = {
    "APIM / AI Gateway": "#0078d4",
    "Logic Apps": "#8764b8",
    "Service Bus": "#00b294",
    "Event Grid": "#ca5010",
    "Functions": "#ffb900",
    "Integration Patterns": "#498205",
    "Industry AI": "#e3008c",
    "Other": "#767676",
}


def _tag_service(item: dict) -> str:
    haystack = f"{item.get('title', '')} {item.get('why_it_matters', '')}".lower()
    for service, keywords in _SERVICE_RULES:
        if any(k in haystack for k in keywords):
            return service
    return _DEFAULT_SERVICE


def _group_by_service(items: list[dict]) -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = {}
    for item in items:
        grouped.setdefault(_tag_service(item), []).append(item)
    return grouped


# ---- plain text --------------------------------------------------------

def digest_to_text(digest: dict, run_date: str | None = None) -> str:
    run_date = run_date or date.today().isoformat()
    must = digest.get("must_know") or []
    watch = digest.get("worth_watching") or []

    lines = [
        f"AI Radar Digest — {run_date}",
        f"{len(must)} must-know · {len(watch)} worth watching",
        "",
        digest.get("intro", "").strip(),
        "",
    ]

    def render_group(items: list[dict], heading: str):
        lines.append(heading)
        lines.append("=" * len(heading))
        grouped = _group_by_service(items)
        for service, group_items in grouped.items():
            lines.append(f"\n[{service}]")
            for item in group_items:
                lines.append(f"* {item.get('title')}")
                lines.append(f"  {item.get('why_it_matters')}")
                lines.append(f"  {item.get('link')}  ({item.get('source')})")
        lines.append("")

    if must:
        render_group(must, "MUST KNOW")
    if watch:
        render_group(watch, "WORTH WATCHING")

    if digest.get("skip_reason") and not must and not watch:
        lines.append(digest["skip_reason"])

    lines.append("Generated by AI Radar Agent.")
    return "\n".join(lines)


# ---- html ---------------------------------------------------------------

def _item_card(item: dict, accent: str) -> str:
    title = item.get("title", "")
    link = item.get("link", "#")
    why = item.get("why_it_matters", "")
    source = item.get("source", "")
    return f"""
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0"
           style="margin:0 0 10px 0;background:#ffffff;border:1px solid #e8e8e8;
                  border-left:3px solid {accent};border-radius:6px;">
      <tr>
        <td style="padding:14px 16px;">
          <a href="{link}" style="color:#1a1a1a;font-size:15px;font-weight:600;
             text-decoration:none;line-height:1.4;">{title}</a>
          <p style="margin:6px 0 8px;color:#4a4a4a;font-size:13.5px;line-height:1.5;">{why}</p>
          <span style="display:inline-block;color:#8a8a8a;font-size:11.5px;
                text-transform:uppercase;letter-spacing:.04em;">{source}</span>
        </td>
      </tr>
    </table>"""


def _service_section(items: list[dict], accent: str) -> str:
    grouped = _group_by_service(items)
    blocks = []
    for service, group_items in grouped.items():
        color = _SERVICE_COLORS.get(service, accent)
        cards = "".join(_item_card(i, color) for i in group_items)
        blocks.append(f"""
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 18px;">
          <tr><td style="padding:0 0 8px 2px;">
            <span style="display:inline-block;background:{color}1a;color:{color};
                  font-size:11px;font-weight:700;letter-spacing:.05em;text-transform:uppercase;
                  padding:3px 9px;border-radius:12px;">{service}</span>
          </td></tr>
          <tr><td>{cards}</td></tr>
        </table>""")
    return "".join(blocks)


def digest_to_html(digest: dict, run_date: str | None = None) -> str:
    run_date = run_date or date.today().isoformat()
    must = digest.get("must_know") or []
    watch = digest.get("worth_watching") or []

    must_html = _service_section(must, "#d13438") if must else \
        '<p style="color:#8a8a8a;font-size:14px;">Nothing urgent today.</p>'
    watch_html = _service_section(watch, "#0078d4") if watch else \
        '<p style="color:#8a8a8a;font-size:14px;">No extra items.</p>'

    return f"""<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#eef1f4;font-family:'Segoe UI',Arial,sans-serif;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#eef1f4;padding:24px 0;">
    <tr>
      <td align="center">
        <table role="presentation" width="640" cellpadding="0" cellspacing="0"
               style="max-width:640px;width:100%;background:#ffffff;border-radius:10px;overflow:hidden;
                      box-shadow:0 1px 3px rgba(0,0,0,0.08);">

          <!-- header -->
          <tr>
            <td style="background:linear-gradient(135deg,#0b3d91,#0078d4);padding:28px 32px;">
              <p style="margin:0 0 6px;color:#cfe4ff;font-size:11px;font-weight:700;
                        letter-spacing:.12em;text-transform:uppercase;">AI Radar</p>
              <h1 style="margin:0;color:#ffffff;font-size:22px;font-weight:700;">
                Digest — {run_date}
              </h1>
              <p style="margin:10px 0 0;color:#d8e7fb;font-size:13px;">
                {len(must)} must-know &nbsp;·&nbsp; {len(watch)} worth watching
              </p>
            </td>
          </tr>

          <!-- intro -->
          <tr>
            <td style="padding:24px 32px 4px;">
              <p style="margin:0;color:#333;font-size:15px;line-height:1.6;">{digest.get("intro","")}</p>
            </td>
          </tr>

          <!-- must know -->
          <tr>
            <td style="padding:20px 32px 4px;">
              <h2 style="margin:0 0 12px;font-size:14px;color:#d13438;font-weight:700;
                         letter-spacing:.03em;text-transform:uppercase;border-bottom:2px solid #f3d3d4;
                         padding-bottom:6px;">Must Know</h2>
              {must_html}
            </td>
          </tr>

          <!-- worth watching -->
          <tr>
            <td style="padding:8px 32px 24px;">
              <h2 style="margin:0 0 12px;font-size:14px;color:#0078d4;font-weight:700;
                         letter-spacing:.03em;text-transform:uppercase;border-bottom:2px solid #cfe4ff;
                         padding-bottom:6px;">Worth Watching</h2>
              {watch_html}
            </td>
          </tr>

          <!-- footer -->
          <tr>
            <td style="padding:16px 32px 24px;border-top:1px solid #eee;">
              <p style="margin:0;color:#9a9a9a;font-size:11.5px;">
                Generated by AI Radar Agent · Azure used only for the LLM.
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>"""
