"""
summarize.py
------------
Send new items to Azure Foundry gpt-4.1-mini and get a ranked digest
aimed at an Azure integration developer.
"""
from __future__ import annotations

import json
import os
from datetime import date

from openai import AzureOpenAI, OpenAI


SYSTEM_PROMPT = """You are AI Radar for Sunny, an Azure integration developer.
He cares about: Azure API Management, Logic Apps, Service Bus, Event Grid,
Azure Functions, Integration Service Environment patterns, AI gateway / MCP
in APIM, connectors, and how industry AI changes affect integration work.

Given raw news items, produce a plain-language daily digest.

Return JSON only with this shape:
{
  "intro": "2-4 sentences on what mattered today for an Azure integration developer",
  "must_know": [
    {
      "title": "short title",
      "why_it_matters": "1-2 sentences tied to integration work",
      "link": "original url",
      "source": "source name"
    }
  ],
  "worth_watching": [
    {
      "title": "short title",
      "why_it_matters": "1 sentence",
      "link": "original url",
      "source": "source name"
    }
  ],
  "skip_reason": "optional one-liner if the day was quiet"
}

Rules:
- Prefer primary Microsoft / Azure sources over reprints
- Rank APIM, Logic Apps, Service Bus, Functions, Event Grid, AI-gateway first
- Industry AI news only if it changes tools, models, or architecture he might use
- No hype, no emojis, no invented facts
- If an item is a noisy marketing post, leave it out
- Use the provided links unchanged
- Keep must_know to at most 6 items, worth_watching to at most 6
"""


def _client():
    endpoint = os.environ["AZURE_OPENAI_ENDPOINT"].rstrip("/")
    api_key = os.environ["AZURE_OPENAI_API_KEY"]
    api_version = os.environ.get("AZURE_OPENAI_API_VERSION", "2024-10-21")

    # Foundry v1-style endpoint
    if endpoint.endswith("/openai/v1") or "services.ai.azure.com" in endpoint:
        base = endpoint if endpoint.endswith("/openai/v1") else f"{endpoint}/openai/v1"
        return OpenAI(base_url=base if base.endswith("/") else base + "/", api_key=api_key)

    return AzureOpenAI(
        azure_endpoint=endpoint,
        api_key=api_key,
        api_version=api_version,
    )


def summarize_items(items: list[dict]) -> dict:
    if not items:
        return {
            "intro": "No new items passed the filter today.",
            "must_know": [],
            "worth_watching": [],
            "skip_reason": "Quiet day — state file already had these links.",
        }

    deployment = os.environ.get("AZURE_OPENAI_DEPLOYMENT", "gpt-4.1-mini")
    payload = [
        {
            "source": item.get("source"),
            "type": item.get("type"),
            "title": item.get("title"),
            "link": item.get("link"),
            "published": item.get("published"),
            "summary": item.get("summary", "")[:500],
        }
        for item in items[:40]
    ]

    client = _client()
    response = client.chat.completions.create(
        model=deployment,
        temperature=0.2,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {
                "role": "user",
                "content": (
                    f"Date: {date.today().isoformat()}\n"
                    f"Items:\n{json.dumps(payload, ensure_ascii=False)}"
                ),
            },
        ],
    )
    raw = response.choices[0].message.content or "{}"
    data = json.loads(raw)
    data.setdefault("intro", "")
    data.setdefault("must_know", [])
    data.setdefault("worth_watching", [])
    return data


def digest_to_text(digest: dict, run_date: str | None = None) -> str:
    run_date = run_date or date.today().isoformat()
    lines = [f"AI Radar Digest — {run_date}", "", digest.get("intro", "").strip(), ""]

    must = digest.get("must_know") or []
    if must:
        lines.append("MUST KNOW")
        lines.append("---------")
        for item in must:
            lines.append(f"* {item.get('title')}")
            lines.append(f"  {item.get('why_it_matters')}")
            lines.append(f"  {item.get('link')}  ({item.get('source')})")
            lines.append("")

    watch = digest.get("worth_watching") or []
    if watch:
        lines.append("WORTH WATCHING")
        lines.append("--------------")
        for item in watch:
            lines.append(f"* {item.get('title')}")
            lines.append(f"  {item.get('why_it_matters')}")
            lines.append(f"  {item.get('link')}  ({item.get('source')})")
            lines.append("")

    if digest.get("skip_reason") and not must and not watch:
        lines.append(digest["skip_reason"])

    lines.append("Generated by AI Radar Agent.")
    return "\n".join(lines)


def digest_to_html(digest: dict, run_date: str | None = None) -> str:
    run_date = run_date or date.today().isoformat()

    def items_html(items):
        blocks = []
        for item in items:
            title = item.get("title", "")
            link = item.get("link", "#")
            why = item.get("why_it_matters", "")
            source = item.get("source", "")
            blocks.append(
                f'<p style="margin:0 0 16px 0;font-size:15px;line-height:1.5;">'
                f'<a href="{link}" style="color:#0b3d91;font-weight:700;text-decoration:none;">{title}</a><br>'
                f"{why}<br>"
                f'<span style="color:#666;font-size:12px;">{source}</span></p>'
            )
        return "\n".join(blocks)

    must = items_html(digest.get("must_know") or [])
    watch = items_html(digest.get("worth_watching") or [])
    return f"""<!DOCTYPE html>
<html><body style="font-family:Segoe UI,Arial,sans-serif;color:#222;background:#f4f4f4;margin:0;padding:24px;">
  <div style="max-width:640px;margin:0 auto;background:#fff;padding:28px;border:1px solid #e1e1e1;">
    <p style="margin:0 0 4px;color:#0078d4;font-size:12px;letter-spacing:.08em;text-transform:uppercase;">AI Radar</p>
    <h1 style="margin:0 0 16px;font-size:24px;">Your AI Radar Digest – {run_date}</h1>
    <p style="font-size:16px;line-height:1.55;">{digest.get("intro","")}</p>
    <h2 style="font-size:16px;border-bottom:1px solid #eee;padding-bottom:6px;">Must know</h2>
    {must or "<p>Nothing urgent today.</p>"}
    <h2 style="font-size:16px;border-bottom:1px solid #eee;padding-bottom:6px;">Worth watching</h2>
    {watch or "<p>No extra items.</p>"}
    <p style="color:#888;font-size:12px;margin-top:28px;">Generated by AI Radar Agent. Azure used only for the LLM.</p>
  </div>
</body></html>"""
